//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by View.rc
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_VIEW_DIALOG					102

#define IDC_NICKNAME_BOX				9999
#define IDC_NEW_GAME_BUTTON				9998
#define IDC_JOIN_GAME_BUTTON			9997
#define IDC_RECOVER_LAST_GAME_BUTTON	9996
#define IDC_TRUCO_BUTTON				9995
#define IDC_GAME_CODE_BOX				9991
#define IDC_START_NEW_GAME_BUTTON		9990
#define IDC_START_JOIN_GAME_BUTTON		9989
#define IDC_BACK_BUTTON_NEW_GAME		9988
#define IDC_BACK_BUTTON_JOIN_GAME		9987
#define IDC_YOUR_CARD_ONE_BUTTON		9986
#define IDC_YOUR_CARD_TWO_BUTTON		9985
#define IDC_YOUR_CARD_THREE_BUTTON		9984
#define IDC_YOUR_CARD_COVER_ONE_BUTTON		9983
#define IDC_YOUR_CARD_COVER_TWO_BUTTON		9982
#define IDC_YOUR_CARD_COVER_THREE_BUTTON	9981
#define IDC_LEAVE_GAME_BUTTON			9980
#define IDC_COPY_TO_CLIPBOARD_BUTTON	9979
#define IDC_SHOW_MENU_GAME_BUTTON		9978

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
